# Backendin peruskuva (Python)
FROM python:3.9

# Työskentelyhakemisto
WORKDIR /app

# Poetryn asennus ja riippuvuudet
COPY pyproject.toml poetry.lock* /app/
RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Kopioi backendin koodi
COPY . /app

# Avaa portti ja määritä käynnistyskomento
EXPOSE 8000
CMD ["python", "app.py"]
