# Description: Dockerfile for the frontend application
FROM node:16

# Set working directory
WORKDIR /app

#  Copy src/ui
COPY ./ ./

# Install dependencies
RUN npm ci

# Build the application
RUN npm run build

# Expose port and start the application
EXPOSE 3000
CMD ["npm", "start"]